@startuml
left to right direction
actor "Client" as C

rectangle CanBankX {
  usecase "UC-01: Inscription & KYC" as UC01
  usecase "UC-02: Authentification & MFA" as UC02
  usecase "UC-03: Ouverture de compte" as UC03
  usecase "UC-04: Consultation Soldes/Historique" as UC04
  usecase "UC-05: Virement Bancaire" as UC05
}

C --> UC01 : Fournit données (NAS, adresse) [cite: 83]
C --> UC02 : OTP / MFA [cite: 94]
C --> UC03 : Sélection type compte [cite: 102]
C --> UC04 : Sélection compte [cite: 111]
C --> UC05 : Saisie montant/bénéficiaire [cite: 119]
@enduml